### ISSUE TITLE
Crash when creating modded entities when creating list of valid targets

### ISSUE THREAD

**Issue by WillR27** [WillR27/Blocklings#11]
This only happens in multiplayer but not singleplayer. Needs fixing either way.

Found by AnotherPlayer#1080.

`java.lang.NullPointerException
at net.minecraft.item.crafting.Ingredient$TagList.func_199799_a(Ingredient.java:272)
at net.minecraft.item.crafting.Ingredient.lambda$new$4(Ingredient.java:47)
at net.minecraft.item.crafting.Ingredient$$Lambda$2432/474994030.test(Unknown Source)
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:47)
at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:153)
at com.github.alexthe666.alexsmobs.entity.EntityCapuchinMonkey.<init>(EntityCapuchinMonkey.java:67)
at com.github.alexthe666.alexsmobs.entity.AMEntityRegistry$$Lambda$4270/1439934427.create(Unknown Source)
at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:445)
at com.willr27.blocklings.entity.EntityUtil.init(EntityUtil.java:45)
at com.willr27.blocklings.events.ForgeEventBusEvents.onWorldLoad(ForgeEventBusEvents.java:41)
at net.minecraftforge.eventbus.ASMEventHandler_768_ForgeEventBusEvents_onWorldLoad_Load.invoke(.dynamic)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
at net.minecraftforge.eventbus.EventBus$$Lambda$2998/1174511944.invoke(Unknown Source)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
at net.minecraft.client.world.ClientWorld.<init>(ClientWorld.java:108)
at net.minecraft.client.network.play.ClientPlayNetHandler.func_147282_a(ClientPlayNetHandler.java:375)
at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:110)
at net.minecraft.network.play.server.SJoinGamePacket.func_148833_a(SourceFile:18)
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
at net.minecraft.network.PacketThreadUtil$$Lambda$15834/1457538170.run(Unknown Source)
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
at net.minecraft.client.main.Main.main(Main.java:184)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/818609427.call(Unknown Source)
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)`

**Comment by WillR27** [comment]
Might have been fixed by a40afb9405b9c9c1b6292e46b163bc76e1127cd4 but it needs properly testing.

**Comment by WillR27** [comment]
Closing after testing on a server.
