### ISSUE TITLE
Crash when attacking a mob

### ISSUE THREAD

**Issue by Owlmighty** [WillR27/Blocklings#11]
1.12.2
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2019-05-29 11:08:22 BRT
Description: Ticking entity

java.lang.NullPointerException
    at com.blocklings.entities.BlocklingAIAttackMelee.updateTask(BlocklingAIAttackMelee.java:159)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at com.blocklings.entities.EntityBlockling.onLivingUpdate(EntityBlockling.java:552)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at com.blocklings.entities.EntityBlockling.onUpdate(EntityBlockling.java:672)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zcd000(World.java:5118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

full crash report link: https://pastebin.com/upVYCnv0

**Comment by WenXin20** [comment]
I got this crash today as well.
