### ISSUE TITLE
Crash when 2 blocklings are chopping trees

### ISSUE THREAD

**Issue by WillR27** [WillR27/Blocklings#12]
Found by Thispikmin#9044

2 blocklings were chopping trees when the crash occurred.

`java.lang.NullPointerException: Ticking entity
at com.willr27.blocklings.goal.goals.BlocklingWoodcutGoal.recalcPath(BlocklingWoodcutGoal.java:292) ~[?:1.0] {re:classloading}
at com.willr27.blocklings.goal.goals.BlocklingGatherGoal.func_75246_d(BlocklingGatherGoal.java:134) ~[?:1.0] {re:classloading}
at com.willr27.blocklings.goal.goals.BlocklingWoodcutGoal.func_75246_d(BlocklingWoodcutGoal.java:95) ~[?:1.0] {re:classloading}
at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$6434/1665762175.accept(Unknown Source) ~[?:?] {}
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {re:computing_frames}
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading}
at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:classloading}
at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading}
at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading}
at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading}
at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B}
at com.willr27.blocklings.entity.entities.blockling.BlocklingEntity.func_70071_h_(BlocklingEntity.java:321) ~[?:1.0] `

**Comment by WillR27** [comment]
After #7 which involved a lot of AI changes, I think this might be fixed. Closing for now.
