### ISSUE TITLE
a crash log

### ISSUE THREAD

**Issue by ycxtdxy** [WillR27/Blocklings#8]
[17:41:41] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.blocklings.entities.EntityBlockling.setName(Ljava/lang/String;)V
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: com.blocklings.entities.EntityBlockling.setName(Ljava/lang/String;)V
        at com.blocklings.entities.EntityBlockling.setTamed(EntityBlockling.java:1117) ~[EntityBlockling.class:?]
        at com.blocklings.entities.EntityBlockling.func_184645_a(EntityBlockling.java:703) ~[EntityBlockling.class:?]
        at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1227) ~[vq.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199) ~[aed.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1073) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by WillR27** [comment]
Thanks for the report @ycxtdxy. Can you tell me what you were doing when this happened. Was it when you spawned a blockling item, or tried taming a blocking or something else?

**Comment by ycxtdxy** [comment]
This happened when i spawned a tamed blockling, and when i turned it to hunt,guard,follow. In both cases the blockling refused to do anything but stands there. In the second case it did cleared the area then became immobile.

[crash-2019-05-06_00.04.50-server.txt](https://github.com/WillR27/Blocklings/files/3161708/crash-2019-05-06_00.04.50-server.txt)

**Comment by WillR27** [comment]
OK, thanks, I will look into this.
